services:
  backend:
    image: ghcr.io/simonwep/genesis:v1.3.1@sha256:57d3df842f9f877f200b8fa28ba9cbf0b9b4a126ee917da3d34f2a3679459958
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/app/.data:rw
    command: start
    environment:
      - GENESIS_PORT
      - GENESIS_DB_PATH
      - GENESIS_CREATE_USERS
      - GENESIS_AUTHORIZED_URIS
      - GENESIS_JWT_SECRET
      - GENESIS_JWT_TOKEN_EXPIRATION
      - GENESIS_JWT_COOKIE_ALLOW_HTTP
      - GENESIS_USERNAME_PATTERN
      - GENESIS_KEY_PATTERN
      - GENESIS_DATA_MAX_SIZE
      - GENESIS_KEYS_PER_USER
      - GENESIS_GIN_MODE
      - GENESIS_LOG_MODE

  frontend:
    image: ghcr.io/simonwep/ocular:v1.5@sha256:ee7a7a4272b37a1bc212a96c2057b3f5e66191f9c521296c8fd0a10373af77c6
    restart: on-failure

  nginx:
    image: nginx:1.24-alpine@sha256:77e5d4a6ad906c5d3793764085706577fa705b1dc6f244ea0241c4b5e2155385
    restart: on-failure
    ports:
      - "3957:80"
    volumes:
      - ${APP_DATA_DIR}/config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
