version: '3.9'

services:
  app_proxy:
    environment:
      APP_HOST: denny-grist_server_1
      APP_PORT: 8484
      PROXY_AUTH_ADD: "false"
  server:
    image: gristlabs/grist:1.2.1@sha256:a96916d6a70601ab86fba6eb1fef7023b206001f023622c4f22616ecfd01588c
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/persist
