version: '3.9'

services:
  app_proxy:
    environment:
      APP_HOST: denny-wallos_web_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"
  web:
    image: bellamy/wallos:2.32.0@sha256:d7a0d1240243c8878bbe4b6a207e59793a14ccd556c12ded8825f1cd1d777fbe
    restart: on-failure
    environment:
      TZ: Europe/Berlin
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/www/html/db
      - ${APP_DATA_DIR}/data/logos:/var/www/html/images/uploads/logos
