version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-paisa_web_1
      APP_PORT: 7500
  web:
    image: ananthakumaran/paisa:v0.7.1@sha256:b5b7e7b8d3309a63ce65bfa16111b46fc3d13d817ccdc3d990c90180627f3275
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/root/Documents/paisa/