version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-excalidraw_web_1
      APP_PORT: 80

  web:
    image: excalidraw/excalidraw@sha256:fae667864717a415e7474b5f757ffb50e63a81cfc1a2fbcf905ecbd137d0dbba
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data/excalidraw

#https://github.com/excalidraw/excalidraw.git   - no arm64 image available
