version: "3.9"
 
services:
  server:
    image: 1dev/server:11.3.2@sha256:cf4b18997ef116fcf38f5f07257b53ebc5a9b69462f142dd9f3798a9cebf0ba0
    volumes:
      - ${APP_DATA_DIR}/var/run/docker.sock:/var/run/docker.sock:rw
      - ${APP_DATA_DIR}/onedev:/opt/onedev:rw
    ports:
      - 6610:6610
      - 6611:6611
    restart: on-failure
