version: '3.9'

services:
  app_proxy:
    environment:
      APP_HOST: denny-answer_web_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"
  web:
    image: apache/answer:1.4.0@sha256:b73a7ecbb53a8e19d0b121117144db5864358d83df857a7e6899e7689cc1f3fc
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/answer-data:/data
