version: '3.9'

services:
  app_proxy:
    environment:
      APP_HOST: denny-cyberchef_web_1
      APP_PORT: 8000
      PROXY_AUTH_ADD: "false"
  web:
    image: mpepping/cyberchef:v10.19.4@sha256:91e04eaaa1ba1eac6b8e410d6f7b340e1ea0450d48ccbb52ec67ce6faa3672c5
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/data