version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-drawio_web_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"
  web:
    image: jgraph/drawio:24.7.17@sha256:3e14dbd7818bb2222ef93d920809771dbbdc1bf8e1d8794c99314ad9a922eeb6
    restart: on-failure
    healthcheck:
     test: curl -f http://umbrel.local:5022/ || exit 1
    mem_limit: 4g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true