version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-opengist_server_1
      APP_PORT: 6157
      PROXY_AUTH_ADD: "false"
  server:
    image: ghcr.io/thomiceli/opengist:1.8.1@sha256:6b86920c48ecb929f91ecaf3b168bb51941c30ac77a70fa88ec600ccefb5668a
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/opengist
