version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-spacedrive_server_1
      APP_PORT: 8080
  server:
    image: ghcr.io/spacedriveapp/spacedrive/server:0.4.2@sha256:fd3bc896f3a5b8e429e008cedde361d6b9468c48d8c81996fdb1d99e90e0837b
    restart: on-failure
    volumes:
      - ${UMBREL_ROOT}/var/spacedrive:/var/spacedrive
    environment:
      - SD_AUTH=disabled
      - TZ=Europe/Berlin
