version: '3.7'
services:
  fileflows:
    image: revenz/fileflows
    restart: unless-stopped
    ports:
      - "19200:5000"
    environment:
      - TZ=Europe/Berlin
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/fileflows:/temp
      - ${APP_DATA_DIR}/data/fileflows:/app/Data
      - ${APP_DATA_DIR}/data/fileflows:/app/Logs
