---
services:
  rustdesk:
    image: lscr.io/linuxserver/rustdesk:latest
    container_name: rustdesk
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /path/to/config:/config
    ports:
      - 3044:3000
      - 3045:3001
    restart: on-failure
