services:
  app_proxy:
    environment:
      APP_HOST: denny-zoraxy_server_1
      APP_PORT: 8000
      PROXY_AUTH_ADD: "false"
  server:
    image: zoraxydocker/zoraxy:v3.1.2@sha256:38f23c5a507542bbd6eac0492bf6456be2004015594ca270a1a5998c8a377b74
    restart: on-failure
   #ports: -> The proxy service is listening on port 8400
      # 8480:80
      # 8443:443
      # 8400:8000
    volumes:
      - ${APP_DATA_DIR}/config/:/opt/zoraxy/config/
      # ${APP_DATA_DIR}/zerotier/config/:/var/lib/zerotier-one/ -> If you are not using ZeroTier, this directory is irrelevant.
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    environment:
      FASTGEOIP: "false"
      ZEROTIER: "false"

      #⚠️ Zoraxy setup is working fine, but without HTTPS and ZeroTier support.
