version: '3.9'

services:
  app_proxy:
    environment:
      APP_HOST: denny-serge_web_1
      APP_PORT: 8008
      PROXY_AUTH_ADD: "false"
  web:
    image: ghcr.io/serge-chat/serge:0.9@sha256:469d8f6e1a43b95428c922221e93b76ff4c3866abd57d1a2a87ac842989eb047
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/weights:/usr/src/app/weights
      - ${APP_DATA_DIR}/datadb:/data/db/
