version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: denny-kiwix_web_1
      APP_PORT: 8080
  web:
    image: ghcr.io/kiwix/kiwix-serve:3.7.0@sha256:ebf9b935eb1301661289ff0dc7a17c6406b0ef0602ff7ca1c9d9187dbae81abe
    restart: on-failure
    command: 'wikipedia_en_100_mini_2024-06.zim' #OPTIONAL
    volumes:
      - "${APP_DATA_DIR}/data/zim:/data:rw"
