version: '3.9'

services:
  app_proxy:
    environment:
      APP_HOST: denny-atheos_server_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"
  server:
    image: hlsiira/atheos:latest@sha256:d7ac44b0ac88eb8878f784414cd50ac7b6330734812617fd9663f3edd2fb54b2
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
