services:
  convertx:
    image: ghcr.io/c4illin/convertx:v0.6.0@sha256:32318b22cd6208033b54fe98fa00544a3d78bd7676a97713b799317eb646e8d3
    container_name: convertx
    restart: on-failure
    ports:
      - "13000:3000"
    environment: # Defaults are listed below. All are optional.
      - ACCOUNT_REGISTRATION=false # true or false, doesn't matter for the first account (e.g. keep this to false if you only want one account)
      - JWT_SECRET=aLongAndSecretStringUsedToSignTheJSONWebToken1234 # will use randomUUID() by default
      - HTTP_ALLOWED=true # setting this to true is unsafe, only set this to true locally
      - ALLOW_UNAUTHENTICATED=true # allows anyone to use the service without logging in, only set this to true locally
      - AUTO_DELETE_EVERY_N_HOURS=24 # checks every n hours for files older then n hours and deletes them, set to 0 to disable
    volumes:
      - ${APP_DATA_DIR}/data/convertx:/app/data
